<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Epoch.Oracle.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Epoch.Testing\Epoch.Testing.csproj" />
    <ProjectReference Include="..\\..\\src\\Epoch.Core\\Epoch.Core.csproj" />
    <ProjectReference Include="..\\..\\src\\Epoch.Content\\Epoch.Content.csproj" />
  </ItemGroup>

</Project>
