<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Epoch.Content</AssemblyName>
    <RootNamespace>Epoch.Content</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Epoch.Core\Epoch.Core.csproj" />
  </ItemGroup>

</Project>
